version: "3.9"

services:
  acai_bark_service:
    build: .
    container_name:acai_bark_service
    ports:
      - "5000:5000"
    environment:
      - ALLOWED_ORIGINS=http://localhost,http://localhost:3000,*
      - HOST=0.0.0.0
      - PORT=5000
